In [1]:
fh=open('students.txt')
data=fh.read()
print('1',data)
data=fh.read()
print('2',data)
fh.close()

1 name     python     c     java
ayyappa    90       70     60
lakshmi    70       60     30
ram        90       90     80
2 


In [2]:
fh=open('students.txt') # by default read mode
print('cursor position before read',fh.tell()) # it tells about the current positon of cursor 0th Position 
fh.read()
print('cursor position after read',fh.tell()) # it tells about the current positon of cursor nth Position 
fh.close()

cursor position before read 0
cursor position after read 120


In [3]:
fh=open('students.txt') # by default read mode
print('cursor position before read',fh.tell()) # it tells about the current positon of cursor 0th Position 
fh.seek(10)
print('cursor position before read',fh.tell()) # it tells about the current positon of cursor 10th Position 
fh.read()
print('cursor position after read',fh.tell()) # it tells about the current positon of cursor nth(last) Position 
fh.close()

cursor position before read 0
cursor position before read 10
cursor position after read 120


In [7]:
# to read first line from the file 
fh=open('students.txt')
print(fh.readline())
fh.close()


name     python     c     java



In [9]:
# to read second line from the file
fh=open('students.txt')
fh.readline()
print(fh.readline())
fh.close()

ayyappa    90       70     60



In [11]:
fh=open('students.txt')
print(fh.readlines())
fh.close()

['name     python     c     java\n', 'ayyappa    90       70     60\n', 'lakshmi    70       60     30\n', 'ram        90       90     80']


In [12]:
fh=open('students.txt')
data=fh.read()
print(data)
fh.close()

name     python     c     java
ayyappa    90       70     60
lakshmi    70       60     30
ram        90       90     80


In [15]:
fh=open('students.txt','r+')
data=fh.read()
fh.write('Sri Rama sri ramaaaa')
fh.close()

## Regular Expressions

In [16]:
import re

#### re.search(str_pattern,str_data)

In [26]:
name='Sai ram sai ram'
print(re.search('s',name))
print(re.search('S',name))
print(re.search('m s',name))


<re.Match object; span=(8, 9), match='s'>
<re.Match object; span=(0, 1), match='S'>
<re.Match object; span=(6, 9), match='m s'>


In [29]:
name2='Sri Rama'
print(re.search('a',name2))

<re.Match object; span=(5, 6), match='a'>


In [30]:
name2='SriRama'
print(re.match('Sri',name2))

<re.Match object; span=(0, 3), match='Sri'>


In [31]:
name ='sairam'
print(re.findall('a',name))

['a', 'a']


## Special Charecters in Regular Expression

In [32]:
# Dot(.) for single charecter
print(re.search('.','sairam'))
print(re.search('.',""))
print(re.search('...','sairam'))


<re.Match object; span=(0, 1), match='s'>
None
<re.Match object; span=(0, 3), match='sai'>


In [33]:
# ^ 

print(re.search('.','sairam'))

<re.Match object; span=(0, 1), match='s'>


In [34]:
name1='sairam'
name2='sreeram'
name3 = 'ram'
name4 = 'raam'
print(re.search('...m$',name1))
print(re.search('...m$',name2))
print(re.search('...m$',name3))
print(re.search('...m$',name4))

<re.Match object; span=(2, 6), match='iram'>
<re.Match object; span=(3, 7), match='eram'>
None
<re.Match object; span=(0, 4), match='raam'>


In [35]:
names=['apples','oranges','grapes','bananas','lemons']
print(names)

['apples', 'oranges', 'grapes', 'bananas', 'lemons']


In [37]:
print(re.search('.....s$',names))

TypeError: expected string or bytes-like object

In [38]:
print(list(names))

['apples', 'oranges', 'grapes', 'bananas', 'lemons']


In [40]:
for each in list(names):
    print(re.search('.....s$',each))

<re.Match object; span=(0, 6), match='apples'>
<re.Match object; span=(1, 7), match='ranges'>
<re.Match object; span=(0, 6), match='grapes'>
<re.Match object; span=(1, 7), match='ananas'>
<re.Match object; span=(0, 6), match='lemons'>


In [42]:
for item in names:
    if re.search('^.....s$',item):
        print(item)

apples
grapes
lemons


In [45]:
##{min,max)

print(re.search('a{4}','baabaaba'))
print(re.search('a{4}','aa'))
print(re.search('a{4}','aaaaaa'))


None
None
<re.Match object; span=(0, 4), match='aaaa'>


## validating mobile number , must contain 10 digits

In [48]:
print(re.search('^\d{10}$','1234567890'))
print(re.search('^\d{10}$','1234567890123'))
print(re.search('^\d{10}$','1234567'))

<re.Match object; span=(0, 10), match='1234567890'>
None
None


In [51]:
print(re.search('[9]','sairam678234'))

<re.Match object; span=(8, 9), match='8'>


In [54]:
print(re.search('[k-o]','sai982123'))

None


In [55]:
re.search('[^429]','4298')

<re.Match object; span=(3, 4), match='8'>

In [58]:
#validating indian mobile number
print(re.search('^[6-9]\d{9}$','9848484848'))
print(re.search('^[6-9]\d{9}$','6848484848'))
print(re.search('^[6-9]\d{9}$','7848484848'))
print(re.search('^[6-9]\d{9}$','8848484848'))
print(re.search('^[6-9]\d{9}$','848484848'))
print(re.search('^[6-9]\d{9}$','4848484848'))
print(re.search('^[6-9]\d{9}$','09848484848'))
print(re.search('^[6-9]\d{9}$','29848484848'))

<re.Match object; span=(0, 10), match='9848484848'>
<re.Match object; span=(0, 10), match='6848484848'>
<re.Match object; span=(0, 10), match='7848484848'>
<re.Match object; span=(0, 10), match='8848484848'>
None
None
None
None


In [59]:
web_content=""" 
abc 123
hi 456 hello78
thanks
"""
print(web_content)

 
abc 123
hi 456 hello78
thanks



In [71]:
s=0
for each in list(web_content):
      if re.search('^[0-9]',each):
        s+=int(each)
print(s)

36


In [72]:
print(re.findall('\d',web_content))

['1', '2', '3', '4', '5', '6', '7', '8']


In [73]:
print(sum(list(map(int,re.findall('\d',web_content)))))

36


In [76]:
print(re.search('\D','rama123sai'))

<re.Match object; span=(0, 1), match='r'>


In [77]:
print(web_content)

 
abc 123
hi 456 hello78
thanks



In [88]:
print(web_content)
print('Total Number of charecter = ',len(web_content))
print('Number of integer         = ',len(re.findall('[0-9]',web_content)))
print('Number of Charecter       = ',len(re.findall('[\D]',web_content)))
print('Number of space = ', len(re.findall('\s',web_content)))
print('Number of charecter excluding space = ',len(re.findall('\S',web_content)))

 
abc 123
hi 456 hello78
thanks

Total Number of charecter =  32
Number of integer         =  8
Number of Charecter       =  24
Number of space =  8
Number of charecter excluding space =  24


In [90]:
print(web_content)
print('Total charecter = ',web_content)
print('integer  = ',re.findall('[0-9]',web_content))
print('Charecter= ',re.findall('[\D]',web_content))
print('space = ', re.findall('\s',web_content))
print('excluding space = ',re.findall('\S',web_content))

 
abc 123
hi 456 hello78
thanks

Total charecter =   
abc 123
hi 456 hello78
thanks

integer  =  ['1', '2', '3', '4', '5', '6', '7', '8']
Charecter=  [' ', '\n', 'a', 'b', 'c', ' ', '\n', 'h', 'i', ' ', ' ', 'h', 'e', 'l', 'l', 'o', '\n', 't', 'h', 'a', 'n', 'k', 's', '\n']
space =  [' ', '\n', ' ', '\n', ' ', ' ', '\n', '\n']
excluding space =  ['a', 'b', 'c', '1', '2', '3', 'h', 'i', '4', '5', '6', 'h', 'e', 'l', 'l', 'o', '7', '8', 't', 'h', 'a', 'n', 'k', 's']


In [97]:
print(re.search('\W','$    & A sai'))

<re.Match object; span=(0, 1), match='$'>


In [100]:
print(re.search('a*','bcde'))

<re.Match object; span=(0, 0), match=''>


In [105]:
# * is zero  or more
#select the data which contain strarting s and ending i
name1='si'
name2='saai'
name3='sreei'
name4='sreeeeee'
print(re.search('^s.*i$',name1))
print(re.search('^s.*i$',name2))
print(re.search('^s.*i$',name3))
print(re.search('^s.*i$',name4))

<re.Match object; span=(0, 2), match='si'>
<re.Match object; span=(0, 4), match='saai'>
<re.Match object; span=(0, 5), match='sreei'>
None


In [108]:
# + is one or more
print(re.search('a+','bbbabaaccaa'))
print(re.search('a+','bbbaabaccaa'))
print(re.search('a+','bbbaaaaaabccaa'))


<re.Match object; span=(3, 4), match='a'>
<re.Match object; span=(3, 5), match='aa'>
<re.Match object; span=(3, 9), match='aaaaaa'>


## mODULES

In [109]:
import project

In [110]:
project.welcome('Sri Rama')

'welcome Sri Rama'

In [111]:
project.add(34,45)

79

In [112]:
project.PI

3.14

# nUMPY

In [114]:
A=[[1,2],[3,4]]
B=[[3,4],[4,5]]
print(A)
print(B)

[[1, 2], [3, 4]]
[[3, 4], [4, 5]]


In [115]:
import numpy as np

In [116]:
values = [1,2,3]
a1 = np.array(values)
print(a1)

[1 2 3]


In [117]:
# shap of the array
a1.shape

(3,)

In [118]:
values = [[1,2,3]]
a2 = np.array(values)
print(a2)
print(a2.shape)

[[1 2 3]]
(1, 3)


In [120]:
v1 = [[1,2],[3,4]]
a1 = np.array(v1)
v2 = [[2,1],[4,3]]
a2 = np.array(v2)
print(a1)
print()
print(a2)

[[1 2]
 [3 4]]

[[2 1]
 [4 3]]


In [121]:
a1+2

array([[3, 4],
       [5, 6]])

In [122]:
a1

array([[1, 2],
       [3, 4]])

In [123]:
a1+=2

In [124]:
a1

array([[3, 4],
       [5, 6]])

In [125]:
a1[0]
a1[1]

array([5, 6])

In [126]:
a1[0]

array([3, 4])

In [127]:
a1[1]

array([5, 6])

In [128]:
a1[0][0]

3

In [129]:
a1[0][0]=10

In [130]:
a1[0][0]

10

In [131]:
a1

array([[10,  4],
       [ 5,  6]])

In [132]:

a2

array([[2, 1],
       [4, 3]])

In [133]:
#addition of matrix
a1+a2

array([[12,  5],
       [ 9,  9]])

In [134]:
# Sub
a1-a2

array([[8, 3],
       [1, 3]])

In [135]:
# multiplication but not matix multiplication
# this is item to item
a1*a2

array([[20,  4],
       [20, 18]])

In [138]:
# Actual Matix Multiplication need to use the .dot()
a1.dot(a2)

array([[36, 22],
       [34, 23]])

In [139]:
a1

array([[10,  4],
       [ 5,  6]])

In [140]:
a2

array([[2, 1],
       [4, 3]])